RANDOM_SEED = 150595

CHANNELS = 1
SAMPLE_RATE = 16000
CLIP_DURATION_MS = 1000
TIME_SHIFT_MS = 0

MAX_NUM_WAVS_PER_CLASS = 2**27 - 1  # ~134M
SILENCE_LABEL = '_silence_'
SILENCE_INDEX = 0
UNKNOWN_WORD_LABEL = '_unknown_'
UNKNOWN_WORD_INDEX = 1
BACKGROUND_NOISE_DIR_NAME = '_background_noise_'

SILENCE_PERCENTAGE = 10
UNKNOWN_PERCENTAGE = 10
VALIDATION_PERCENTAGE = 10
TESTING_PERCENTAGE = 10

BACKGROUND_FREQUENCY = 0.8
BACKGROUND_VOLUME = 0.05
