RANDOM_SEED = 150595

CHANNELS = 1
SAMPLE_RATE = 16_000
CLIP_DURATION_MS = 1000
TIME_SHIFT_MS = 0

MAX_NUM_WAVS_PER_CLASS = 2**27 - 1  # ~134M
BACKGROUND_NOISE_DIR_NAME = 'background_noise'
SILENCE_LABEL = '_silence_'
VOCAL_WORD_LABEL = 'vocal'
KEYWORD_LABEL = 'keyword'
REAL_NEGATIVE_LABEL = 'real_negative'

NEGATIVE_WORD_INDEX = 0
POSITIVE_WORD_INDEX = 1
